version: '3.8'

services:
  gaiascan:
    build: .
    container_name: gaiascan
    ports:
      - "5050:5050"
    volumes:
      - ./uploads:/app/uploads
      - ./static/img:/app/static/img
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped 